### ISSUE TITLE
IRIS displays "and" as a label for MI item type when row label is blank

### ISSUE THREAD

**Issue by hbgwhite** [SmarterApp/TDS_IRIS#17]
When there is no label for a row in an MI item, IRIS renders a label with the text "   and   " below the checkbox answer choices:

![image](https://user-images.githubusercontent.com/1069704/31091341-7e3f23fc-a75f-11e7-80c1-67ab6f63b52e.png)

Here is the item xml being rendered:

`<?xml version="1.0" encoding="UTF-8"?>
<itemrelease version="2.0">
   <item bankkey="187" format="mi" id="123" version="11">
      <attriblist>
         <attrib attid="itm_item_id">
            <name>Item: ITS ID</name>
            <val>123</val>
            <desc/>
         </attrib>
         <attrib attid="itm_att_Item Format">
            <name>Item: Item Format</name>
            <val>MI</val>
            <desc/>
         </attrib>
         <attrib attid="itm_att_Answer Key">
            <name>Item: Answer Key</name>
            <val>MI</val>
            <desc/>
         </attrib>
         <attrib attid="itm_att_Page Layout">
            <name>Item: Page Layout</name>
            <val>21</val>
            <desc/>
         </attrib>
         <attrib attid="itm_att_Response Type">
            <name>Item: Response Type</name>
            <val>TableMatch</val>
            <desc/>
         </attrib>
      </attriblist>
      <MachineRubric filename="Item_123_v11.qrx" xmlns:its-scripts="urn:its-scripts"/>
      <content language="ENU" version="2.0" xmlns:its-scripts="urn:its-scripts">
         <qti spec="itemBody">
            <![CDATA[<matchInteraction maxAssociations="" minAssociations="1" responseIdentifier="RESPONSE"><prompt/><simpleMatchSet><simpleAssociableChoice identifier="1"><p style=""><br/><span style="font-weight:bold; ">row one</span></p></simpleAssociableChoice><simpleAssociableChoice identifier="2"><p style=""><br/><span style="font-weight:bold; "></span></p></simpleAssociableChoice><simpleAssociableChoice identifier="3"><p style=""><br/><span style="font-weight:bold; "></span></p></simpleAssociableChoice></simpleMatchSet><simpleMatchSet><simpleAssociableChoice identifier="a"><p style="font-weight:bold; ">column one</p></simpleAssociableChoice></simpleMatchSet></matchInteraction>]]>
         </qti>
         <stem>
            <![CDATA[<p >prompt text</p>]]>
         </stem>
      </content>
   </item>
</itemrelease>`

**Comment by alexlepinski** [comment]
What version of IRiS are you running? I'm not able to reproduce this issue with and without row label.

**Comment by hbgwhite** [comment]
The version is 1.1.3. I've solved the display issue by removing the <br/> elements from the incoming CData.

<br/> elements are rendered as "and" labels when rows do not have titles. I'm not sure why that is, but with the workaround a fix is no longer urgent.
