### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by esotrope** [SmarterApp/TDS_IRIS#4]
<h4>Build Command</h4>

```bash
mvn -e clean package
```

<h4>Stacktrace</h4>

> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time: 15.326 s
> [INFO] Finished at: 2017-03-31T13:01:27-07:00
> [INFO] Final Memory: 13M/208M
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal on project iris: Could not resolve dependencies for project org.opentestsystem.delivery:iris:war:1.0.3: The following artifacts could not be resolved: org.opentestsystem.delivery:student:war:2.1.0, org.opentestsystem.delivery:item-renderer:jar:0.0.1, org.opentestsystem.delivery:tds-itemselection-aironline:jar:0.0.1, org.opentestsystem.delivery:tds-dll-api:jar:0.0.1, org.opentestsystem.delivery:tds-dll-mssql:jar:0.0.1, org.opentestsystem.delivery:tds-dll-mysql:jar:0.0.1, AIR:ResourceBundler:jar:0.0.1, org.opentestsystem.delivery:tds-itemselection-common:jar:0.0.1, org.opentestsystem.delivery:item-scoring-api:jar:1.1.0, org.opentestsystem.delivery:item-scoring-engine:jar:1.1.0, org.opentestsystem.delivery:testscoring:jar:0.0.1, AIR.SpellCheck:spellcheck:jar:0.0.1, org.opentestsystem.delivery:student.library:jar:0.0.1: Could not find artifact org.opentestsystem.delivery:student:war:2.1.0 in central (https://airdev.artifactoryonline.com/airdev/libs-releases) -> [Help 1]
> ...
> Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.opentestsystem.delivery:student:war:2.1.0 in central (https://airdev.artifactoryonline.com/airdev/libs-releases)

<h4>Environment</h4>

- Java 1.8.0_112
- Maven 3.3.9
- [settings.txt (~/.m2/settings.xml renamed with .txt for upload)](https://github.com/SmarterApp/TDS_IRIS/files/886787/settings.txt)

**Comment by alexdean201** [comment]
It looks like the student.war file v2.1.0 needs to be uploaded to the Artificatory repo.  A review of all the dependencies will need to happen to ensure that a build can occur.

**Comment by alexlepinski** [comment]
fixed with release IRIS 3.2
