### ISSUE TITLE
Missing Script webaudio.worker

### ISSUE THREAD

**Issue by alexlepinski** [SmarterApp/TDS_IRIS#7]
Version 2.0 has an issue with importing webaudio.worker.js script

**Comment by alexlepinski** [comment]
@jtreuting is this still an issue? This has to do with iris scripts importing the webaudio.worker.js from the root instead of relative path.

**Comment by jtreuting** [comment]
Yes we still see this 404 in the console when using IRIS.  It is most likely related to IRIS not being able to play the audio items when they are being previewed.

**Comment by alexlepinski** [comment]
@jtreuting this will be fixed in the next release

**Comment by jtreuting** [comment]
Great thanks!
